#! /usr/bin/env python3

import sys
import time

runtime = time.time() + int(sys.argv[1])

while True:
    time.sleep(1)
    print("E's not dead yet!")
    if time.time() > runtime:
        raise SystemExit('Finished OK!')
